version: '3.8'

services:
  backend:
    build: ./backend
    expose:
      - "8000"
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/static
      - media_volume:/media

  frontend:
    build: ./frontend
    volumes:
      - frontend_dist:/app/dist 

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    - frontend_dist:/usr/share/nginx/html
    - static_volume:/static
    - media_volume:/media
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume:
  frontend_dist:
