# Generated by Django 5.2.2 on 2025-06-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userbook',
            options={'verbose_name': 'Элемент списка', 'verbose_name_plural': 'Списки'},
        ),
        migrations.AlterModelOptions(
            name='userbookstatus',
            options={'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
    ]
